name: Publish

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - uses: actions/configure-pages@v5

            - uses: actions/jekyll-build-pages@v1
              with:
                  source: ./www
                  destination: ./_site

            - uses: actions/upload-pages-artifact@v3

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to pages
              id: deployment
              uses: actions/deploy-pages@v4

